### ISSUE TITLE
Safari on iOS and macOS does weird things in the sidebar

### ISSUE THREAD

**Issue by hynek** [pradyunsg/furo#16] opened 2020-10-05 09:37 UTC
When hovering an item on macOS Safari (or tapping it on iOS Safari), you get a weird artifact on the left side, that's not there on other browsers:

![Screenshot 2020-10-05 at 10 37 00](https://user-images.githubusercontent.com/41240/95063805-bf87c680-06f6-11eb-80d1-e0618309c23c.png)

**Comment by pradyunsg** [comment] 2020-10-05 09:52
Caused by 08fdd525bfa56936189f0268d64923ce4f9b8604. Why can't we have nice things? :(

**Comment by pradyunsg** [comment] 2020-10-05 09:57
Fixed in fcd81025a8b1980a9a8ec6b79af8280a83638f21. Closing!

**Closed by pradyunsg** 2020-10-05 09:57 UTC
Labels: bug
