### ISSUE TITLE
sphinx-copybutton moves when code cell scrolls horizontally

### ISSUE THREAD

**Issue by goodmami** [pradyunsg/furo#41] opened 2020-11-26 08:30 UTC
**Describe the bug**

In this theme, and not in Alabaster (the demo site for sphinx-copybutton), the copy button image moves when the user scrolls the code cell horizontally.

**To Reproduce**

1. Enable sphinx-copybutton
2. Create a code cell with long lines
3. Scroll

You can try it out here: https://wn.readthedocs.io/en/latest/

**Expected behavior**

The copy button image should stay put, as it does here: https://sphinx-copybutton.readthedocs.io/en/latest/

**Screenshots**

![scroll-sphinx-copybutton](https://user-images.githubusercontent.com/1428419/100324151-c4376f80-3001-11eb-9b2b-d3cbd9c3f89c.gif)

**Desktop (please complete the following information):**

- OS: Pop!_OS 20.04 (Ubuntu derivative)
- Browser: Both Firefox 83.0 and Chrome 87.0 show the same thing
- Version: `furo-2020.11.19b18`

**Smartphone (please complete the following information):**

- Device: iPhone7
- OS: iOS14.1
- Browser Safari

**Additional context**

Looking at the CSS, I think this has to do with the copybutton's containing `div.highlight` element having `overflow: auto` while in the Alabaster theme it's the sibling `pre` element that has the property.

**Comment by pradyunsg** [comment] 2020-11-28 00:14
@choldgraf @chrisjsewell Any suggestions on whether this should be accomodated for in Furo, or sphinx-copybutton?

I ask because I feel like I can't decide. ;)

**Comment by pradyunsg** [comment] 2020-12-06 18:03
Nudge to trigger a notification to Chris. ;)

**Comment by choldgraf** [comment] 2020-12-06 20:12
@pradyunsg if you can find a fix that works on the sphinx-copybutton side then I think that'd be the most useful place for it to happen. I guess this issue is unique to Furo (at least, doesn't exist for the alabaster theme) but we can test against Furo if we implement https://github.com/executablebooks/meta/issues/199 as well

**Comment by pradyunsg** [comment] 2020-12-28 11:40
Fixed on Furo's end, in 9496d05896b417001a2d25e95034a49b840b5912. I think it's a simple-enough fix that I don't feel like we need something on sphinx-copybutton's end. :)

**Closed by pradyunsg** 2020-12-28 11:40 UTC
Labels: bug

**Comment by pradyunsg** [comment] 2020-12-28 16:31
Noting here that this fix caused a regression: #70.
