### ISSUE TITLE
Incorrect render for multiple terms of glossary

### ISSUE THREAD

**Issue by sirkonst** [pradyunsg/furo#43] opened 2020-11-27 07:01 UTC
**Describe the bug**

Glossary supports display [multiple terms](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html?highlight=multiple%20terms#glossary) but `furo` renders it incorrectly.

Checked on `2020.11.19b18` version.

**To Reproduce**

1. Add glossary with multiple term:

```
.. glossary::

    RC
    release candidate
        The environment separated and isolated from
        production intended for developing as well as manual and
        automated testing.
```

2. Render html by `furo` theme.
3. Incorrect result:

![image](https://user-images.githubusercontent.com/69752/100419765-35c0fd80-3096-11eb-8a78-97a2cbfe3344.png)

**Expected behavior**

Something like this:

![image](https://user-images.githubusercontent.com/69752/100419800-44a7b000-3096-11eb-8bc7-4e6fe68f8505.png)

PS: furo is grate theme! Thank for work!

**Comment by dgw** [comment] 2020-11-27 07:10
Duplicate of #35

**Closed** 2020-11-27 08:54 UTC
Labels: bug

**Comment by pradyunsg** [comment] 2020-11-27 23:52
Released the fix as part of beta 19. Let me know if that's not good-enough. :)

**Comment by sirkonst** [comment] 2020-11-30 11:57
Fantastic, thank!

**Comment by cblegare** [comment] 2020-12-01 15:21
Yes! thats fixed
