### ISSUE TITLE
Search box isn't a fixed height so can become small with toc under

### ISSUE THREAD

**Issue by boxed** [pradyunsg/furo#71] opened 2021-01-01 23:38 UTC
**Describe the bug**
In certain window sizes and with certain sizes of side bar the search input field gets too small vertically and the table of contents can start to draw below it.

**To Reproduce**

1. go to https://pradyunsg.me/furo/quickstart/
2. resize the window to be very small height wise
3. scroll the table of contents

The reason this happens to me is that I have lots of stuff in the table of contents and a vertically big logo in the sidebar. So it happens even with fairly normal window sizes for me.

**Expected behavior**
Search field should be some kind of fixed size.

**Screenshots**

<img width="243" alt="Screen Shot 2021-01-02 at 00 33 33" src="https://user-images.githubusercontent.com/332428/103447956-c214a080-4c92-11eb-8af7-3f3ec73095c8.png">
<img width="293" alt="Screen Shot 2021-01-02 at 00 29 26" src="https://user-images.githubusercontent.com/332428/103447957-c476fa80-4c92-11eb-9f0c-476abb190d07.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Safari
- Version: 2020.12.30b24

**Comment by pradyunsg** [comment] 2021-03-14 07:33
Ah, Safari. I'll need to put a flex-shrink: 0 somewhere, I think.

Thanks for a clear report! ^.^

**Comment by pradyunsg** [comment] 2021-03-18 20:19
![Screenshot 2021-03-18 at 8 19 11 PM](https://user-images.githubusercontent.com/3275593/111692293-35a46380-8827-11eb-9f86-a18ec0357d42.png)

I can't seem to reproduce this.

**Comment by boxed** [comment] 2021-03-19 13:17
You need to scroll the menu a bit. Quickstart is the top most menu item. Scroll down so that you can't see it anymore.

**Comment by pradyunsg** [comment] 2021-03-19 18:20
![Screenshot 2021-03-19 at 6 18 05 PM](https://user-images.githubusercontent.com/3275593/111825562-82e40c00-88df-11eb-8873-250a26032601.png)

Nope, that's not sufficient to reproduce this either. :/

---

What version of Safari is this? Notes below on how to find the version number:

> Choose Safari from the top menu, and About Safari. The version number will be on the window that pops up.

**Comment by dgw** [comment] 2021-03-19 19:38
Oh, this is only reproducible in Safari? Best of luck! I ended up submitting feedback to Apple about the last issue like this on the site at work. Still awaiting reply, a month later.

**Comment by pradyunsg** [comment] 2021-03-19 20:53
FWIW, I'm unable to reproduce this on Safari too. 🤷🏻‍♂️

**Comment by boxed** [comment] 2021-03-20 06:46
I'm on big sur. Safari 14.

**Comment by pradyunsg** [comment] 2021-03-20 07:44
Huh. So am I. :/

Does it still happen for you if you press command+shift+R on the page? Could it be a copy that's been poorly cached by your browser?

**Comment by yeraydiazdiaz** [comment] 2021-05-06 10:47
I can't reproduce this either on Catalina Safari 14.1

<img width="1114" alt="Screenshot 2021-05-06 at 11 47 06" src="https://user-images.githubusercontent.com/6739793/117286202-c9c29c80-ae60-11eb-9559-5b252e587ade.png">

**Comment by pradyunsg** [comment] 2021-06-18 18:59
Closing since this doesn't seem to be reproducible.

**Closed by pradyunsg** 2021-06-18 18:59 UTC
Labels: bug, needs info
