### ISSUE TITLE
Left-side menu gets pushed into the logo if it doesn't fit

### ISSUE THREAD

**Issue by hynek** [pradyunsg/furo#14] opened 2020-10-05 07:48 UTC
Sorry for not using your template but I think this screenshot speaks for itself:

![Screenshot 2020-10-05 at 08 46 03](https://user-images.githubusercontent.com/41240/95052688-46cd3e00-06e7-11eb-8636-c336d4be67f4.png)

This happens when I resize the window such that the menu doesn't fit anymore.

(I've found it while using web inspector.)

**Comment by pradyunsg** [comment] 2020-10-05 09:16
Whoops. Look like a big introduced in ca8912a1b41ce609a5a7063ce282e5d124e844bb.

**Comment by pradyunsg** [comment] 2020-10-05 10:53
Hmm... Is this at a resolution smaller than ~250px-300px? None of the desktop browsers go below 300px (unless you have a quirky build / OS) and none of the mobile display resolutions that I can find go below 300px either.

**Comment by hynek** [comment] 2020-10-05 11:54
Could be? I ran into it through web inspector that resizes the usable area.` ¯\_(ツ)_/¯`

**Comment by pradyunsg** [comment] 2020-10-05 12:11
Yea, I can't reproduce this at higher resolutions -- and such narrow viewports don't show up "in the wild" so I'm not super interested in solving this TBH.

FWIW, such narrow viewports would also break the entire navigation structure (since you can't see the overlay even -- which is necessary to be able to hide the content).

**Comment by hynek** [comment] 2020-10-05 14:47
Wait "narrow"? It's full width. The problem is just about height:
<img width="1680" alt="Screenshot 2020-10-05 at 15 46 30@2x" src="https://user-images.githubusercontent.com/41240/95094578-f7583380-0721-11eb-9bbe-42762e2f2873.png">

**Comment by pradyunsg** [comment] 2020-10-05 14:58
AHHHH. What browser?

I can't reproduce this on FF or Brave (i.e. Chrome's Blink without the Google-isms).

**Comment by hynek** [comment] 2020-10-05 15:00
Take a wild guess :D

**Comment by pradyunsg** [comment] 2020-10-05 15:14
\>.<

Fixed in c42b78f.

**Closed by pradyunsg** 2020-10-05 15:14 UTC
Labels: bug
