### ISSUE TITLE
Add user end customizability for code block coloring and highlighting of the inline code block

### ISSUE THREAD

**Issue by mdurrani808** [pradyunsg/furo#68] opened 2020-12-27 18:42 UTC
**Is your feature request related to a problem? Please describe.**
The current variable that controls the highlighting of the inline code block and general code block coloring always looks out of place:
![image](https://user-images.githubusercontent.com/46766905/103177508-3097cf80-4849-11eb-823f-dcdde049d951.png)
(this screenshot is from the PhotonVision documentation)

**Describe the solution you'd like**
CSS variable that the user can control in conf.py to change both of these.

**Describe alternatives you've considered**
Have a set color that is used for light/dark mode that cannot be controlled by the user but still would fit in.

**Comment by pradyunsg** [comment] 2020-12-27 18:48
Thanks for filing this issue, but it's unclear to me which variable are you referring to here. Could you clarify which CSS variable you are referring to?

**Comment by mdurrani808** [comment] 2020-12-27 21:22
The highlighting is included in the CSS variable of color-background-secondary. I think it should be separated into two different things that can adapt based on light/dark mode. Then you end up with issues like this: 
![image](https://user-images.githubusercontent.com/46766905/103179998-8b3c2600-485f-11eb-83da-7225662eb6da.png)

![image](https://user-images.githubusercontent.com/46766905/103180002-94c58e00-485f-11eb-914b-af923e563c31.png)

For the code block, I dont think there is a CSS variable for it right now (that the user can tweak to my knowledge) and I think there should be one. (unless I am missing something). Thank you for the prompt response!

**Comment by dgw** [comment] 2020-12-27 21:25
@mdurrani808 relevant snippets of HTML and/or source (Markdown/rST) text would help pin down exactly what you're talking about. Screenshots don't give much visibility into _what's_ being rendered.

**Comment by pradyunsg** [comment] 2020-12-27 21:42
Indeed. Please provide a reproducer for your issue, with step-by-step instructions on how to generate the documentation.

**Comment by mdurrani808** [comment] 2020-12-27 22:11
My apologies for all the confusion. The following gist should be more helpful. This is a sample of one of our pages you will see when building our documentation and our full source code is below. It includes a code block and inline code block. Full source code is below. https://gist.github.com/mdurrani808/83d6aee7ac99df41124e0c4e84abf9da

To reproduce:
The repo is here: https://github.com/mdurrani808/photonvision-docs
Instructions to reproduce/build are here: https://docs.photonvision.org/en/latest/docs/other/contributing/photonvision-docs/building-docs.html

Use the repo url I provided instead of the one we list in the documentation.

**Comment by pradyunsg** [comment] 2020-12-28 11:31
Do you want the background color for the code block and inline code block to be syncronized? If so, you'll need to customise the pygments theme being used by Sphinx for highlighting code blocks with Furo's inline code block CSS variable.

See https://pradyunsg.me/furo/customisation/colors/#code-block-styling for details (note that #49's fix hasn't been released yet).

**Comment by pradyunsg** [comment] 2020-12-28 17:04
I _think_ you're asking for something like d97ce720aec73b2c8740770ab3d1b9d50c80d7a2?

**Comment by mdurrani808** [comment] 2020-12-28 19:56
I think that's it yeah. If what I'm asking isn't possible/doesnt make any sense, just close this issue as I don't wanna waste your time.

This is basically what I'm asking:
![test](https://user-images.githubusercontent.com/46766905/103239885-d49e7b00-491c-11eb-9ae0-a6daa2df5ce7.png)

**Comment by pradyunsg** [comment] 2020-12-28 20:53
That white in the tabbed UI is coming from sphinx-tabs - nothing that I'd do in Furo about that. You're gonna have to write your own CSS to override whatever styles sphinx-tabs brings in. 🤷🏻‍♂️

As for the inline code background, that is something that you have set explicitly in conf.py. The aforementioned commit change behaviour in that area, so try building again with the current release of Furo -- it should use the background from the currently active code theme.

---

All the fixes I've mentioned are in the latest release, so just go ahead and try that. I don't think there's going to be anything to do in this issue in Furo's end right now, so let me know if you have any further questions. :)

**Comment by hynek** [comment] 2020-12-30 11:58
Can it be that the code background for inline code is not setable individually? <https://www.attrs.org/en/latest/index.html> looks a bit silly compared to <https://www.attrs.org/en/stable/>. Basically like a search is one and has highlighted many words…

**Comment by pradyunsg** [comment] 2020-12-30 12:03
Ah fun. I forgot that folks would want to use the non-default Sphinx themes with Furo. :)

**Comment by pradyunsg** [comment] 2020-12-30 12:10
Reverted that change, and made the inline-code-block background configurable via a CSS variable. Released in https://pypi.org/project/furo/2020.12.30b24/. 😅

**Comment by hynek** [comment] 2020-12-30 12:28
> Ah fun. I forgot that folks would want to use the non-default Sphinx themes with Furo. :)

Not sure what you mean by that? 🤔

**Comment by pradyunsg** [comment] 2020-12-30 13:33
You're setting a pygments_style in conf.py, which overrides the default set by Furo in its own theme.conf. :)

**Comment by hynek** [comment] 2020-12-31 09:44
Ooof, pretty sure that's from the default skeleton.

**Comment by pradyunsg** [comment] 2021-02-06 09:00
> made the inline-code-block background configurable via a CSS variable.

Closing since this is now possible.

**Closed by pradyunsg** 2021-02-06 09:00 UTC
Labels: enhancement, needs info
