### ISSUE TITLE
Add simple option to force light or dark theme

### ISSUE THREAD

**Issue by johnthagen** [pradyunsg/furo#100] opened 2021-03-13 18:18 UTC
**Is your feature request related to a problem? Please describe.**

From the docs:

> While the mechanism for switching between light/dark mode is not configurable

For some projects, the documentation theme may wish to always match another part of a project. For example, if a user creates a web application that uses a dark theme, they may want to enforce that a dark theme is also always used regardless of client configuration.

In our use case, we have a web application frontend that uses a dark theme, and we'd like the built user guide to also always be shown as a dark theme as well.

**Describe the solution you'd like**

Add a configuration option:

```py
html_theme_options = {
    "force_theme": "dark";  # Also can be "light"
}
```

If `"force_theme"` is not set, `furo` defaults to the the current operation of using the client's browser to decide.

**Comment by dgw** [comment] 2021-03-13 18:24
See #24 & #28

**Comment by pradyunsg** [comment] 2021-03-14 07:31
Thanks for filing this issue! It is a duplicate of #28, so I'm going to close this. Feel free to drop a comment on that issue. :)

**Closed by pradyunsg** 2021-03-14 07:31 UTC
Labels: enhancement
